### ISSUE TITLE
Google News改版，脚本失效

### ISSUE THREAD

**Issue by lychichem** [zanetu/direct_google#10]
因为Google News的改版，脚本无法在Google News页面上去除跳转链接

**Comment by zanetu** [comment]
v3.5可解码部分链接。非base64编码的链接目前无法解码，举例：

1. `https://news.google.com/articles/CAIiEP3mC0iuRNhH9bQgc8yLWKsqFggEKg4IACoGCAowl6p7MN-zCTCOvRU`
跳转后链接：
`https://www.theguardian.com/commentisfree/2018/jun/20/video-games-addictive-disorder-diagnosis`

2. `https://news.google.com/articles/CBMi-AFodHRwczovL2hrLmZpbmFuY2UueWFob28uY29tL25ld3MvJUUzJTgwJTkwJUU3JTkwJTg2JUU4JUIyJUExJUU1JTgwJThCJUU2JUExJTg4JUUzJTgwJTkxJUU1JTg2JTgwJUU1JTk0JUFFJUU1JTg1JUE5JUU1JTgwJThCJUU3JUFDJUFDJUU0JUI4JTgwJUU1JTlGJThFJUU1JTk2JUFFJUU0JUJEJThELSVFNiU4RiU5QiVFNiVBOCU5MyVFOCU4NyVCMyVFNiVCOCVBRiVFNSVCMyVCNiVFNiU5RCVCMSVFNSU4RCU5QS0wNDAwMjc2MjMuaHRtbNIBAA`
跳转后链接：
`https://hk.finance.yahoo.com/news/%E3%80%90%E7%90%86%E8%B2%A1%E5%80%8B%E6%A1%88%E3%80%91%E5%86%80%E5%94%AE%E5%85%A9%E5%80%8B%E7%AC%AC%E4%B8%80%E5%9F%8E%E5%96%AE%E4%BD%8D-%E6%8F%9B%E6%A8%93%E8%87%B3%E6%B8%AF%E5%B3%B6%E6%9D%B1%E5%8D%9A-040027623.html`

此Issue暂时不要关闭，如果长期无法修复此Issue可能会考虑彻底移除对Google News的支持（有种谷歌百度化的感觉，令人遗憾）。

**Comment by lychichem** [comment]
是啊google news现在连订阅源都找不到了真令人头大

发送自我的iPhone

在 2018年6月21日，23:35，zanetu <notifications@github.com<mailto:notifications@github.com>> 写道：


v3.5可解码部分链接。非base64编码的链接目前无法解码，举例：

  1.  https://news.google.com/articles/CAIiEP3mC0iuRNhH9bQgc8yLWKsqFggEKg4IACoGCAowl6p7MN-zCTCOvRU
跳转后链接：
https://www.theguardian.com/commentisfree/2018/jun/20/video-games-addictive-disorder-diagnosis

  2.  https://news.google.com/articles/CBMi-AFodHRwczovL2hrLmZpbmFuY2UueWFob28uY29tL25ld3MvJUUzJTgwJTkwJUU3JTkwJTg2JUU4JUIyJUExJUU1JTgwJThCJUU2JUExJTg4JUUzJTgwJTkxJUU1JTg2JTgwJUU1JTk0JUFFJUU1JTg1JUE5JUU1JTgwJThCJUU3JUFDJUFDJUU0JUI4JTgwJUU1JTlGJThFJUU1JTk2JUFFJUU0JUJEJThELSVFNiU4RiU5QiVFNiVBOCU5MyVFOCU4NyVCMyVFNiVCOCVBRiVFNSVCMyVCNiVFNiU5RCVCMSVFNSU4RCU5QS0wNDAwMjc2MjMuaHRtbNIBAA
跳转后链接：
https://hk.finance.yahoo.com/news/%E3%80%90%E7%90%86%E8%B2%A1%E5%80%8B%E6%A1%88%E3%80%91%E5%86%80%E5%94%AE%E5%85%A9%E5%80%8B%E7%AC%AC%E4%B8%80%E5%9F%8E%E5%96%AE%E4%BD%8D-%E6%8F%9B%E6%A8%93%E8%87%B3%E6%B8%AF%E5%B3%B6%E6%9D%B1%E5%8D%9A-040027623.html

此Issue暂时不要关闭，如果长期无法修复此Issue可能会考虑彻底移除对Google News的支持（有种谷歌百度化的感觉，令人遗憾）。
