### ISSUE TITLE
脚本失效（2022.6.18）

### ISSUE THREAD

**Issue by lychichem** [zanetu/direct_google#12]
如题，脚本在Google搜索页失效，具体表现是鼠标滑过的时候能解析出原始链接，但是点击后仍然是先google链接再跳转

**Comment by zanetu** [comment]
最近有点忙，简单看了一下，把beta版里的
`$('a[onmousedown^="return rwt("]').removeAttr('onmousedown')`
改成
`$('a[ping]').removeAttr('ping')`
试试
