### ISSUE TITLE
’此网站可能会损害您的计算机‘导致不是原链接

### ISSUE THREAD

**Issue by wenketel** [zanetu/direct_google#6]
https://www.google.com/search?newwindow=1&safe=off&q=site%3Abt.orzx.im+%E7%BA%B9

https://www.google.com/interstitial?url=http://bt.orzx.im/display.php%3Fid%3D28194

**Comment by zanetu** [comment]
[V2.4](https://rawgit.com/zanetu/direct_google/beta/direct_google.user.js)

**Comment by wenketel** [comment]
谢谢。
